# Generated by Django 2.1 on 2019-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='quantity_available',
            field=models.IntegerField(),
        ),
    ]
