# Generated by Django 2.1 on 2019-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='date',
            field=models.DateField(),
        ),
    ]
