# Generated by Django 2.1 on 2019-07-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_drugs', '0002_auto_20190720_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solddrugs',
            name='drug_id',
        ),
        migrations.RemoveField(
            model_name='solddrugs',
            name='sale_id',
        ),
        migrations.DeleteModel(
            name='SoldDrugs',
        ),
    ]
