# Generated by Django 2.1 on 2019-07-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_drugs', '0004_auto_20190716_2336'),
        ('purchase_drugs', '0003_auto_20190720_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_drugs.Drugs')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_drugs.SaleRecord')),
            ],
        ),
    ]
