# Generated by Django 2.1 on 2019-07-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_drugs', '0004_solddrugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='solddrugs',
            name='drug_id',
        ),
        migrations.RemoveField(
            model_name='solddrugs',
            name='sale_id',
        ),
        migrations.DeleteModel(
            name='SaleRecord',
        ),
        migrations.DeleteModel(
            name='SoldDrugs',
        ),
    ]
