# Generated by Django 2.1 on 2019-07-20 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('select_drugs', '0004_auto_20190716_2336'),
        ('purchase_drugs', '0005_auto_20190720_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_mobile_no', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=150)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_drugs.Drugs')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_drugs.SaleRecord')),
            ],
        ),
    ]
