# Generated by Django 2.1 on 2019-08-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_drugs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='drugs',
        ),
    ]
