# Generated by Django 2.1 on 2019-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile_no', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=30)),
                ('customer_password', models.CharField(max_length=30)),
            ],
        ),
    ]
