# Generated by Django 2.1 on 2019-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20190712_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=30)),
                ('supplier_mobile_no', models.CharField(max_length=30)),
                ('supplier_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
