# Generated by Django 2.1 on 2019-07-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
