# Generated by Django 2.1 on 2019-07-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20190716_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
